# Generated by Django 2.2.6 on 2019-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='question_text',
            field=models.TextField(),
        ),
    ]
