# Generated by Django 2.2.6 on 2019-11-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191111_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='question_text',
            new_name='text',
        ),
    ]
