# Generated by Django 2.2.6 on 2019-11-18 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20191111_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='amount_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.TextField(default='Другое'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
