# Generated by Django 2.2.6 on 2019-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_course_requestregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
