# Generated by Django 2.2.7 on 2019-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20191128_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Название темы')),
                ('difficulty', models.CharField(choices=[('Легкий', 'Легкий'), ('Средний', ''), ('Сложный', '')], default='Легкий', max_length=50)),
                ('description', models.TextField(max_length=800, verbose_name='Описание задачи')),
            ],
        ),
    ]
