# Generated by Django 2.2.7 on 2019-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('Легкий', '1. Легкий'), ('Средний', '2. Средний'), ('Сложный', '3. Сложный')], default='Легкий', max_length=50),
        ),
    ]
