# Generated by Django 2.2.7 on 2019-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20191130_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='f_description',
            field=models.TextField(default='Right something', max_length=2000, verbose_name='Полное описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='s_description',
            field=models.TextField(default='Short description', max_length=200, verbose_name='Наименование задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Название темы'),
        ),
    ]
