# Generated by Django 2.2.7 on 2019-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20191130_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='f_description',
            field=models.TextField(default='Right something', max_length=1000, verbose_name='Полное описание задачи'),
        ),
    ]
