# Generated by Django 2.2.7 on 2019-11-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20191130_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fulldescription',
        ),
    ]
