# Generated by Django 2.2.7 on 2019-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20191130_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Наименование задачи'),
        ),
    ]
