# Generated by Django 2.2.7 on 2019-11-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20191130_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='s_description',
            field=models.CharField(max_length=200, verbose_name='Наименование задачи'),
        ),
    ]
