# Generated by Django 2.2.7 on 2019-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20191130_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('1. Легкий', 'Легкий'), ('2. Средний', 'Средний'), ('3. Сложный', 'Сложный')], default='1. Легкий', max_length=50),
        ),
    ]
